### ISSUE TITLE
Enhancement: Add Twitter login

### ISSUE THREAD

**Issue by ScottishRoss** [ScottishRoss/little_victories#13]
Along with Google Sign-In, users should be able to sign in with a Twitter account.
- Twitter sign-in implemented.
- A new user is created on Twitter sign-in.
- If that Users email already exists (i.e. via Google sign-in), the login details are combined.
- Sign-out of Twitter button added to Preferences.

**Comment by ScottishRoss** [comment]
Of course, have fun my friend!

**Comment by sudo-saksham** [comment]
@ScottishRoss, Twitter Developers project is asking me about the following details :
Website URL
Callback URL
Terms of Service
Privacy Policy

Could you comment the websites of the above required fields?

**Comment by ScottishRoss** [comment]
Website: https://www.littlevictories.app/
Privacy Policy: https://www.littlevictories.app/privacy-policy

I have applied for a Twitter Dev account to get the final URLs, though I'm not sure what the TOS URL is. When I get approved I will let you know.

**Comment by ScottishRoss** [comment]
I'm not sure I can say. Having a quick look around, it may take a few days for approval. I was unaware of this step otherwise I would have done it before.

Can you give me a link to the documentation regarding the TOS URL? If that's something I have to generate I may be able to get it done faster, but the Callback URL would still be blocked until this approval.

**Comment by sudo-saksham** [comment]
Actually, I have no idea how this TOS URL thing works. I didn't come across any documentation that says how to generate it. If I find one I'll let you know.

**Comment by ScottishRoss** [comment]
Thanks. If my dev account gets approved I'll have a look there. Unfortunately, there's not much more I can help you with until that happens. You can try and create one yourself and see if that gets approved first. Those details can be left out of the PR and I can add them in later.

**Comment by ScottishRoss** [comment]
TOS Link: https://www.littlevictories.app/terms-of-service

It will suffice for now. I think that's everything you need, @sudo-saksham?
