### ISSUE TITLE
Enhancement: Facebook sign-in

### ISSUE THREAD

**Issue by ScottishRoss** [ScottishRoss/little_victories#14]
Along with Google Sign-In, users should be able to sign in with a Facebook account.

Facebook sign-in implemented.
A new user is created on Facebook sign-in.
If that Users email already exists (i.e. via Google sign-in), the login details are combined.
Sign-out of Facebook button added to Preferences.

**Comment by sudo-saksham** [comment]
Can you create a separate branch on your repo for this feature? I'll make a PR into that branch itself so that if something's not correct than it won't affect the rest of the code. @ScottishRoss

**Comment by ScottishRoss** [comment]
That's what you're doing. If you clone the repo, create a new branch and work on that. You can then merge that locally to see if it works and raise the PR to the Develop branch on this repo.

**Comment by sudo-saksham** [comment]
Hey, I'm getting this error when I'm logging in with Facebook auth. I'm running this app on Android 11 and I have also implemented this FAQ answer given in the URL, but it's still showing me this and hence the token provided is null. Therefore, I cannot login with Facebook : 
```
W/com.facebook.internal.NativeProtocol( 9966): Apps that target Android API 30+ (Android 11+) cannot call Facebook native apps unless the package visibility needs are declared. Please follow https://developers.facebook.com/docs/android/troubleshooting/#faq_267321845055988 to make the declaration.
```

**Comment by sudo-saksham** [comment]
For the reference, I implemented that suggestion given in the log like this : ![facebook_auth](https://user-images.githubusercontent.com/55953830/139571503-1edb8fc8-79a0-475a-b14f-1776590dcaa8.png)
