### ISSUE TITLE
New Feature: Add Victory also includes icons

### ISSUE THREAD

**Issue by ScottishRoss** [ScottishRoss/little_victories#17]
When celebrating a Victory a user should be able to choose an icon out of a list of Icons.

- Create a new class called "VictoryIcons".
- Fields:
- - Title
- - Icon

Icons (Title / Icon): 
- Happy - sentiment_very_satisfied
- Activity - local_activity
- Outside - nature_people
- Food - restaurant
- Hygiene - bathtub
- Exercise - fitness_center
- Other - help_outline

Add a new field to the Add Victory modal allowing a user to select an Icon. Implement how would like, but I think a horizontal sliding list with each Icon would look good. On select have the icon light up. The default selection should be "Other".

When submitting the Victory, this new field should be populated in Firebase. So AddNewVictory will need to be modified.

In View Victories the ListTile should have the Icon appear on the left of the tile. If there Icon is null it should be the Other icon.

**Comment by sudo-saksham** [comment]
Did you change the design of Adding the victory dialog box to this image on purpose? Because it's creating a ```Pixel Overflow issue``` when keyboard opens. I'm attaching related image and video with this comment. @ScottishRoss

https://user-images.githubusercontent.com/55953830/139504522-b1d170db-d034-4e4a-9425-a64eb8efb599.mp4

![Screenshot_20211030-025900](https://user-images.githubusercontent.com/55953830/139504530-bd5f34fb-2bcb-45d3-a217-0a07f8481a39.png)

**Comment by ScottishRoss** [comment]
Ooh that's interesting @sudo-saksham. That overflow issue doesn't happen for me. If you checkout the develop branch and have a look there, is that issue there?

**Comment by sudo-saksham** [comment]
Are you referring to the occurence of this error in ```develop``` branch code or whether the this is registered as an issue?

**Comment by ScottishRoss** [comment]
@sudo-saksham It's worth checking if this issue exists in Develop, or if it's in your branch and some changes need to be made. If there are any changes that happened to develop (some refactoring changes happened with Hacktoberfest), then it's a combination of those chances and yours, and it'll mean some changes need to be made on your branch.

Though, I am liking the look of the changes your making! It's looking good!

**Comment by sudo-saksham** [comment]
Can you look into the changes I made in this ![PR](https://github.com/ScottishRoss/little_victories/pull/28). I made some changes which you also minimizes this overflow issue. Though, the design might not be much good as I just changed to remove the error. I can work on design and refactoring next if you want. @ScottishRoss

**Comment by ScottishRoss** [comment]
I'll have s look tomorrow @sudo-saksham. Great work so far!

**Comment by sudo-saksham** [comment]
Then, I'll most probably start integrating Facebook login. Let me know if any change needs to be made.

**Comment by ScottishRoss** [comment]
Handled in #37
