### ISSUE TITLE
General Refactoring

### ISSUE THREAD

**Issue by ScottishRoss** [ScottishRoss/little_victories#2]
This project was created when I was first learning Flutter, and as such, there is a lot of improvements that can be made to the code. Any sizable improvements to refactoring a PR can be linked to this ticket, and if I consider it sizable enough I will merge it.

**Comment by devkishor8007** [comment]
Can you assign this to me?

**Comment by ScottishRoss** [comment]
@devkishor8007 have fun! 

For anyone else looking to contribute to this PR, I will assign this to other people as well.
