### ISSUE TITLE
Enhancement: Add intro pages

### ISSUE THREAD

**Issue by ScottishRoss** [ScottishRoss/little_victories#38]
To explain the concept of Little Victories, it would be good to implement an intro sequence to explain the concepts. Using something like https://pub.dev/packages/intro_views_flutter

It should be stored shared_preferences if a user has already been through it. 

Optional: Include a button in Preferences to display the intro pages again.

**Comment by glitchpop-frenzy** [comment]
Hey, can I take this?

**Comment by ScottishRoss** [comment]
Closed by #50
